//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _00000000000000000000000 {
            get {
                object obj = ResourceManager.GetObject("00000000000000000000000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _13_130474_black_credit_card_pay_card_icon_png_transparent {
            get {
                object obj = ResourceManager.GetObject("13-130474_black-credit-card-pay-card-icon-png-transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _22222222222222222 {
            get {
                object obj = ResourceManager.GetObject("22222222222222222", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _31033f89_7407_4fa0_afb8_bb40b833abf0_1_b21c514f1f3942c34f66cf6421f27681 {
            get {
                object obj = ResourceManager.GetObject("31033f89-7407-4fa0-afb8-bb40b833abf0_1.b21c514f1f3942c34f66cf6421f27681", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_186372280_80FQAz60eaFojyysih6rlaB7GMmRPG7O {
            get {
                object obj = ResourceManager.GetObject("360_F_186372280_80FQAz60eaFojyysih6rlaB7GMmRPG7O", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _455_4555037_blue_doctor_icon_png_transparent_png {
            get {
                object obj = ResourceManager.GetObject("455-4555037_blue-doctor-icon-png-transparent-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _500_F_217199479_VBxbYYxkX8uxmqQNTZUv9hXJGWsv5BZR {
            get {
                object obj = ResourceManager.GetObject("500_F_217199479_VBxbYYxkX8uxmqQNTZUv9hXJGWsv5BZR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _51pSARpGOML__SY450_ {
            get {
                object obj = ResourceManager.GetObject("51pSARpGOML._SY450_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _613edel31KL__AC_SX679_ {
            get {
                object obj = ResourceManager.GetObject("613edel31KL._AC_SX679_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _64_641423_blue_phone_logo_png_transparent_blue_phone_icon {
            get {
                object obj = ResourceManager.GetObject("64-641423_blue-phone-logo-png-transparent-blue-phone-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _800px_COLOURBOX23876936 {
            get {
                object obj = ResourceManager.GetObject("800px_COLOURBOX23876936", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _84_841013_bank_png_blue_bank_icon {
            get {
                object obj = ResourceManager.GetObject("84-841013_bank-png-blue-bank-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9cb450ab_a848_4bf0_8657_91ec2d25c591_8e0629256cf3118d5fd5c4e16aee283a {
            get {
                object obj = ResourceManager.GetObject("9cb450ab-a848-4bf0-8657-91ec2d25c591.8e0629256cf3118d5fd5c4e16aee283a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap age_icon_20181102083837 {
            get {
                object obj = ResourceManager.GetObject("age_icon_20181102083837", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Appointment_Reschedule_Request_Icon_Graphics_11757726_2_580x386 {
            get {
                object obj = ResourceManager.GetObject("Appointment-Reschedule-Request-Icon-Graphics-11757726-2-580x386", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap beautiful_meticulously_designed_email_open_mail_new_email_icon_well_organized_and_fully_editable_vector_icon_WWBBX6 {
            get {
                object obj = ResourceManager.GetObject("beautiful-meticulously-designed-email-open-mail-new-email-icon-well-organized-and" +
                        "-fully-editable-vector-icon-WWBBX6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_tick_icon_vector_symbol_checkmark_isolated_white_background_checked_correct_choice_sign_check_mark_checkbox_pictogram_147212415 {
            get {
                object obj = ResourceManager.GetObject("blue-tick-icon-vector-symbol-checkmark-isolated-white-background-checked-correct-" +
                        "choice-sign-check-mark-checkbox-pictogram-147212415", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card {
            get {
                object obj = ResourceManager.GetObject("card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dextromethophan_400x400 {
            get {
                object obj = ResourceManager.GetObject("Dextromethophan-400x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dextromethorphan_1 {
            get {
                object obj = ResourceManager.GetObject("Dextromethorphan-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dextromethorphan_hbr_chlorpheniramine_maleate_and_phenylephrine_hcl_syrup_500x500 {
            get {
                object obj = ResourceManager.GetObject("dextromethorphan-hbr-chlorpheniramine-maleate-and-phenylephrine-hcl-syrup-500x500" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_icon_card_credit_card_debit_card_visa_card_icon_1320184902260183266_512 {
            get {
                object obj = ResourceManager.GetObject("download-icon-card+credit+card+debit+card+visa+card+icon-1320184902260183266_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap email_icon_png_5 {
            get {
                object obj = ResourceManager.GetObject("email-icon-png-5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fexofenidine_Hcl_Tablets {
            get {
                object obj = ResourceManager.GetObject("Fexofenidine-Hcl-Tablets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gift_card_cion {
            get {
                object obj = ResourceManager.GetObject("gift-card-cion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glycopyrrolate_02mg_1_5x {
            get {
                object obj = ResourceManager.GetObject("Glycopyrrolate-02mg@1.5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap health_care_drug_pharmacist_878852718_1x {
            get {
                object obj = ResourceManager.GetObject("health-care-drug-pharmacist-878852718_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap healthcare_medical_heart_vector_poster_items_medicines_medications_treatments_pills_drugs_pulse_tooth_implant_84192379 {
            get {
                object obj = ResourceManager.GetObject("healthcare-medical-heart-vector-poster-items-medicines-medications-treatments-pil" +
                        "ls-drugs-pulse-tooth-implant-84192379", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hospital_PNG_Transparent_HD_Photo {
            get {
                object obj = ResourceManager.GetObject("Hospital-PNG-Transparent-HD-Photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_3 {
            get {
                object obj = ResourceManager.GetObject("image 3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_31 {
            get {
                object obj = ResourceManager.GetObject("image 31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_32 {
            get {
                object obj = ResourceManager.GetObject("image 32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images_1 {
            get {
                object obj = ResourceManager.GetObject("images 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imodium_ad_caplet {
            get {
                object obj = ResourceManager.GetObject("imodium_ad_caplet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1132087010_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1132087010-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1132087010_612x6121 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1132087010-612x6121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1133376756_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1133376756-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1205256331_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1205256331-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1211308388_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1211308388-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1285912397_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1285912397-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_965546474_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-965546474-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_paypal_computer_icons_logo_paypal_5ac737e8df0e72_9482777915230054169137 {
            get {
                object obj = ResourceManager.GetObject("kisspng-paypal-computer-icons-logo-paypal-5ac737e8df0e72.9482777915230054169137", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap library_credit_card_icon_672259 {
            get {
                object obj = ResourceManager.GetObject("library-credit-card-icon-672259", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Member_Logo {
            get {
                object obj = ResourceManager.GetObject("Member Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Member_Logo1 {
            get {
                object obj = ResourceManager.GetObject("Member Logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap misoprostol_cautelar {
            get {
                object obj = ResourceManager.GetObject("misoprostol-cautelar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap naltima_28naltrexone_29_for_bulk_500x500 {
            get {
                object obj = ResourceManager.GetObject("naltima-28naltrexone-29-for-bulk-500x500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap naltrexone_500x500 {
            get {
                object obj = ResourceManager.GetObject("naltrexone-500x500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paypa {
            get {
                object obj = ResourceManager.GetObject("paypa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pillsandthermometerfeatureimage1600x650 {
            get {
                object obj = ResourceManager.GetObject("pillsandthermometerfeatureimage1600x650", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_the_doctor_examines_the_patient_with_covid_19_symptoms_png_image_5342356 {
            get {
                object obj = ResourceManager.GetObject("pngtree-the-doctor-examines-the-patient-with-covid-19-symptoms-png-image_5342356", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap prescription_rx_recipe_line_icon_medicine_drugs_pills_sign_colorful_outline_concept_blue_orange_thin_color_vector_134564603 {
            get {
                object obj = ResourceManager.GetObject("prescription-rx-recipe-line-icon-medicine-drugs-pills-sign-colorful-outline-conce" +
                        "pt-blue-orange-thin-color-vector-134564603", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_icon_125165 {
            get {
                object obj = ResourceManager.GetObject("search_icon_125165", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_icon_1251651 {
            get {
                object obj = ResourceManager.GetObject("search_icon_1251651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap secure_payment_icon_flat_design_vector_10515661 {
            get {
                object obj = ResourceManager.GetObject("secure-payment-icon-flat-design-vector-10515661", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_photo_group_of_medical_doctors_over_hospital_background_health_care_335039969 {
            get {
                object obj = ResourceManager.GetObject("stock-photo-group-of-medical-doctors-over-hospital-background-health-care-3350399" +
                        "69", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap team_1024x683 {
            get {
                object obj = ResourceManager.GetObject("team-1024x683", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vector {
            get {
                object obj = ResourceManager.GetObject("Vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vector1 {
            get {
                object obj = ResourceManager.GetObject("Vector1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2022_04_16_at_12_15_43_PM {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2022-04-16 at 12.15.43 PM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2022_04_22_at_9_23_45_PM {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2022-04-22 at 9.23.45 PM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap young_people_using_mobile_apps_data_analysis_flat_d_character_concept_web_design_172317108 {
            get {
                object obj = ResourceManager.GetObject("young-people-using-mobile-apps-data-analysis-flat-d-character-concept-web-design-" +
                        "172317108", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
